// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Finoku.API.Models;

public partial class AssetCategory
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Assets> Assets { get; set; } = new List<Assets>();
}