// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Finoku.API.Models;

public partial class Assets
{
    public int Id { get; set; }

    public string Name { get; set; }

    public decimal Amount { get; set; }

    public string Currency { get; set; }

    public decimal PurchasePrice { get; set; }

    public DateTime PurchasedAt { get; set; }

    public int UserId { get; set; }

    public int CategoryId { get; set; }

    public int AssetCategoryId { get; set; }

    public virtual AssetCategory AssetCategory { get; set; }

    public virtual Users User { get; set; }
}