// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Finoku.API.Models;

public partial class ExchangeRates
{
    public int Id { get; set; }

    public string CurrencyPair { get; set; }

    public decimal Rate { get; set; }

    public DateTime LasyUpdated { get; set; }
}