// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Finoku.API.Models;

public partial class FinokuPortfolioDbContext : DbContext
{
    public FinokuPortfolioDbContext(DbContextOptions<FinokuPortfolioDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AssetCategory> AssetCategory { get; set; }

    public virtual DbSet<Assets> Assets { get; set; }

    public virtual DbSet<ExchangeRates> ExchangeRates { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AssetCategory>(entity =>
        {
            entity.Property(e => e.Name).IsRequired();
        });

        modelBuilder.Entity<Assets>(entity =>
        {
            entity.HasIndex(e => e.AssetCategoryId, "IX_Assets_AssetCategoryId");

            entity.HasIndex(e => e.UserId, "IX_Assets_UserId");

            entity.Property(e => e.Amount).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.Currency).IsRequired();
            entity.Property(e => e.Name).IsRequired();
            entity.Property(e => e.PurchasePrice).HasColumnType("decimal(18, 4)");

            entity.HasOne(d => d.AssetCategory).WithMany(p => p.Assets).HasForeignKey(d => d.AssetCategoryId);

            entity.HasOne(d => d.User).WithMany(p => p.Assets).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<ExchangeRates>(entity =>
        {
            entity.Property(e => e.CurrencyPair).IsRequired();
            entity.Property(e => e.Rate).HasColumnType("decimal(18, 4)");
        });

        modelBuilder.Entity<Users>(entity =>
        {
            entity.Property(e => e.Password).IsRequired();
            entity.Property(e => e.Username).IsRequired();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}